### ISSUE TITLE
[Suggestion] Make the main repo a standalone repository instead of a fork

### ISSUE THREAD

**Issue by dvalters** [ourcodingclub/tutorials-in-progress#18]
At the minute the main coding club website/tutorials are a fork of the original template that was used to create the site: i.e. https://github.com/ourcodingclub/ourcodingclub.github.io is forked from https://github.com/ndrewtl/airspace-jekyll

This means peoples contributions/commits don't show up (as it's a fork). We can 'detatch' it and make it 'standalone' so people's commits are counted to coding club.

See: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

> **Commit was made in a fork**
> Commits made in a fork will not count toward your contributions. To make them count, you must do one of the following:
> 
> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support or GitHub Premium Support.
> 

I did this on another repo once and they are really quick to respond, just takes a quick email to them.

**Comment by gndaskalova** [comment]
That is a great idea @dvalters - I just sent them an email to ask for the detachment, thanks very much for the suggestion!

**Comment by gndaskalova** [comment]
We are independent! And the GitHub support staff person was very nice and quick indeed!

**Comment by dvalters** [comment]
Great! 🎉
